# Generated by Django 4.1.2 on 2022-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_product_price',
            field=models.PositiveIntegerField(default=1232),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_tax',
            field=models.FloatField(default=21343),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'sucess'), ('FAILED', 'failed')], default=2),
        ),
    ]
