# Generated by Django 4.1.2 on 2022-11-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
    ]
