# Generated by Django 4.1.2 on 2022-11-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
